# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache

# 2. Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://x.com # jekyll-mentions > service used when @replying
remote_theme: daviddarnes/alembic@main
twitter:
  username: ContactPARIS21 # jekyll-seo-tag > Owners twitter username
author: PARIS21 # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: PARIS21 # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://x.com/ContanctPARIS21
    - https://www.linkedin.com/company/paris21/
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
#timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
#collections:
#   posts:
#     title: Posts # Needed for Siteleaf
#     output: true
#     description: "My thoughts and ideas" # The post list page content
#     feature_text: |
#       Welcome to the blog
#     feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/gender_data_cover.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Gender Data Library - BFA" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/P21_insd_site.svg" # Site logo, also used in jekyll-seo-tag
description: "Gender Data Library" # Site description and default description, also used in jekyll-seo-tag
url: "https://github.com/johannesabele/" # Site url, also used in jekyll-seo-tag
baseurl: "gender-data-use-BFA/"
repo: "" # Site repository, used in jekyll-seo-tag
email: ""
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/P21_icon.ico'
  32: '/assets/logos/P21_icon.ico'
  96: '/assets/logos/P21_icon.ico'
  120: '/assets/logos/P21_icon.ico'
  144: '/assets/logos/P21_icon.ico'
  180: '/assets/logos/P21_icon.ico'
  512: '/assets/logos/P21_icon.ico'
  1024: '/assets/logos/P21_icon.ico'

# 9. Site navigation
navigation_header:
  - title: Home
    url: /
  - title: Gender Data Library
    url: /library/
  - title: Civil Society Organisations - Beta
    url: /csos/
  - title: Methodology
    url: /methodology/
  - title: Search
    url: /search/

navigation_footer:
  - title: Created by PARIS21
    url: https://www.paris21.org/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://x.com/ContanctPARIS21
  LinkedIn: https://www.linkedin.com/company/paris21/

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
